//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.12 at 01:04:06 AM CET 
//


package rs.acs.uns.sw.govrs.client.fx.serverdomain;

import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;
import rs.acs.uns.sw.govrs.client.fx.serverdomain.adapters.StringPropertyAdapter;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for obrazlozenje element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="obrazlozenje">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element name="razlog">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element ref="{http://www.parlament.gov.rs/schema/elementi}ref" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="objasnjene_predlozenog_rjesenja">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element ref="{http://www.parlament.gov.rs/schema/elementi}ref" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="cilj">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element ref="{http://www.parlament.gov.rs/schema/elementi}ref" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="uticaj_na_budzetska_sredstva">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element ref="{http://www.parlament.gov.rs/schema/elementi}ref" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "razlog",
        "objasnjenePredlozenogRjesenja",
        "cilj",
        "uticajNaBudzetskaSredstva"
})
@XmlRootElement(name = "obrazlozenje", namespace = "http://www.parlament.gov.rs/schema/amandman")
public class Explanation {

    @XmlElement(namespace = "http://www.parlament.gov.rs/schema/amandman", required = true)
    @XmlJavaTypeAdapter(StringPropertyAdapter.class)
    protected StringProperty razlog = new SimpleStringProperty();

    @XmlElement(name = "objasnjene_predlozenog_rjesenja", namespace = "http://www.parlament.gov.rs/schema/amandman", required = true)
    @XmlJavaTypeAdapter(StringPropertyAdapter.class)
    protected StringProperty objasnjenePredlozenogRjesenja = new SimpleStringProperty();

    @XmlElement(namespace = "http://www.parlament.gov.rs/schema/amandman", required = true)
    @XmlJavaTypeAdapter(StringPropertyAdapter.class)
    protected StringProperty cilj = new SimpleStringProperty();

    @XmlElement(name = "uticaj_na_budzetska_sredstva", namespace = "http://www.parlament.gov.rs/schema/amandman", required = true)
    @XmlJavaTypeAdapter(StringPropertyAdapter.class)
    protected StringProperty uticajNaBudzetskaSredstva = new SimpleStringProperty();

    /**
     * Gets the value of the razlog property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getRazlog() {
        return razlog.get();
    }

    /**
     * Sets the value of the razlog property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setRazlog(String value) {
        this.razlog.set(value);
    }

    public StringProperty razlogProperty() {
        return razlog;
    }

    /**
     * Gets the value of the objasnjenePredlozenogRjesenja property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getObjasnjenePredlozenogRjesenja() {
        return objasnjenePredlozenogRjesenja.get();
    }

    /**
     * Sets the value of the objasnjenePredlozenogRjesenja property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setObjasnjenePredlozenogRjesenja(String value) {
        this.objasnjenePredlozenogRjesenja.set(value);
    }

    public StringProperty objasnjenjePredlozenogRjesenjaProperty() {
        return objasnjenePredlozenogRjesenja;
    }

    /**
     * Gets the value of the cilj property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCilj() {
        return cilj.get();
    }

    /**
     * Sets the value of the cilj property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCilj(String value) {
        this.cilj.set(value);
    }

    public StringProperty ciljProperty() {
        return cilj;
    }

    /**
     * Gets the value of the uticajNaBudzetskaSredstva property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getUticajNaBudzetskaSredstva() {
        return uticajNaBudzetskaSredstva.get();
    }

    /**
     * Sets the value of the uticajNaBudzetskaSredstva property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setUticajNaBudzetskaSredstva(String value) {
        this.uticajNaBudzetskaSredstva.set(value);
    }

    public StringProperty uticajNaBudzetskaSredstvaProperty() {
        return uticajNaBudzetskaSredstva;
    }

}
