//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.12 at 01:04:06 AM CET 
//


package rs.acs.uns.sw.govrs.client.fx.serverdomain;

import rs.acs.uns.sw.govrs.client.fx.serverdomain.*;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.ac.uns.sw.xml.domain package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.ac.uns.sw.xml.domain
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Law }
     * 
     */
    public Law createLaw() {
        return new Law();
    }

    /**
     * Create an instance of {@link Law.Head }
     * 
     */
    public Law.Head createLawHead() {
        return new Law.Head();
    }

    /**
     * Create an instance of {@link Amendments }
     * 
     */
    public Amendments createAmendments() {
        return new Amendments();
    }

    /**
     * Create an instance of {@link Amendments.Body }
     * 
     */
    public Amendments.Body createAmendmentsBody() {
        return new Amendments.Body();
    }

    /**
     * Create an instance of {@link Amendments.Head }
     * 
     */
    public Amendments.Head createAmendmentsHead() {
        return new Amendments.Head();
    }

    /**
     * Create an instance of {@link Explanation }
     * 
     */
    public Explanation createExplanation() {
        return new Explanation();
    }

    /**
     * Create an instance of {@link Amendment }
     * 
     */
    public Amendment createAmendment() {
        return new Amendment();
    }

    /**
     * Create an instance of {@link Amendment.Body }
     * 
     */
    public Amendment.Body createAmendmentBody() {
        return new Amendment.Body();
    }

    /**
     * Create an instance of {@link Amendment.Head }
     * 
     */
    public Amendment.Head createAmendmentHead() {
        return new Amendment.Head();
    }

    /**
     * Create an instance of {@link Paragraph }
     * 
     */
    public Paragraph createParagraph() {
        return new Paragraph();
    }

    /**
     * Create an instance of {@link Ref }
     * 
     */
    public Ref createRef() {
        return new Ref();
    }

    /**
     * Create an instance of {@link Article }
     * 
     */
    public Article createArticle() {
        return new Article();
    }

    /**
     * Create an instance of {@link Part }
     * 
     */
    public Part createPart() {
        return new Part();
    }

    /**
     * Create an instance of {@link Chapter }
     * 
     */
    public Chapter createChapter() {
        return new Chapter();
    }

    /**
     * Create an instance of {@link Subsection }
     * 
     */
    public Subsection createSubsection() {
        return new Subsection();
    }

    /**
     * Create an instance of {@link Subclause }
     * 
     */
    public Subclause createSubclause() {
        return new Subclause();
    }

    /**
     * Create an instance of {@link Clause }
     * 
     */
    public Clause createClause() {
        return new Clause();
    }

    /**
     * Create an instance of {@link Section }
     * 
     */
    public Section createSection() {
        return new Section();
    }

    /**
     * Create an instance of {@link Item }
     * 
     */
    public Item createItem() {
        return new Item();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link AppUser }
     * 
     */
    public AppUser createAppUser() {
        return new AppUser();
    }

    /**
     * Create an instance of {@link LegalEntity }
     * 
     */
    public LegalEntity createLegalEntity() {
        return new LegalEntity();
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link Individual }
     * 
     */
    public Individual createIndividual() {
        return new Individual();
    }

    /**
     * Create an instance of {@link Law.Body }
     * 
     */
    public Law.Body createLawBody() {
        return new Law.Body();
    }

    /**
     * Create an instance of {@link Law.Head.DatumPredloga }
     * 
     */
    public Law.Head.DatumPredloga createLawHeadDatumPredloga() {
        return new Law.Head.DatumPredloga();
    }

    /**
     * Create an instance of {@link Law.Head.DatumIzglasavanja }
     * 
     */
    public Law.Head.DatumIzglasavanja createLawHeadDatumIzglasavanja() {
        return new Law.Head.DatumIzglasavanja();
    }

    /**
     * Create an instance of {@link Law.Head.Status }
     * 
     */
    public Law.Head.Status createLawHeadStatus() {
        return new Law.Head.Status();
    }

    /**
     * Create an instance of {@link Law.Head.GlasovaZa }
     * 
     */
    public Law.Head.GlasovaZa createLawHeadGlasovaZa() {
        return new Law.Head.GlasovaZa();
    }

    /**
     * Create an instance of {@link Law.Head.GlasovaProtiv }
     * 
     */
    public Law.Head.GlasovaProtiv createLawHeadGlasovaProtiv() {
        return new Law.Head.GlasovaProtiv();
    }

    /**
     * Create an instance of {@link Law.Head.GlasovaSuzdrzani }
     * 
     */
    public Law.Head.GlasovaSuzdrzani createLawHeadGlasovaSuzdrzani() {
        return new Law.Head.GlasovaSuzdrzani();
    }

    /**
     * Create an instance of {@link Law.Head.Podnosilac }
     * 
     */
    public Law.Head.Podnosilac createLawHeadPodnosilac() {
        return new Law.Head.Podnosilac();
    }

    /**
     * Create an instance of {@link Amendments.Body.PravniOsnov }
     * 
     */
    public Amendments.Body.PravniOsnov createAmendmentsBodyPravniOsnov() {
        return new Amendments.Body.PravniOsnov();
    }

    /**
     * Create an instance of {@link Amendments.Head.DatumPredloga }
     * 
     */
    public Amendments.Head.DatumPredloga createAmendmentsHeadDatumPredloga() {
        return new Amendments.Head.DatumPredloga();
    }

    /**
     * Create an instance of {@link Amendments.Head.DatumIzglasavanja }
     * 
     */
    public Amendments.Head.DatumIzglasavanja createAmendmentsHeadDatumIzglasavanja() {
        return new Amendments.Head.DatumIzglasavanja();
    }

    /**
     * Create an instance of {@link Amendments.Head.Status }
     * 
     */
    public Amendments.Head.Status createAmendmentsHeadStatus() {
        return new Amendments.Head.Status();
    }

    /**
     * Create an instance of {@link Amendments.Head.GlasovaZa }
     * 
     */
    public Amendments.Head.GlasovaZa createAmendmentsHeadGlasovaZa() {
        return new Amendments.Head.GlasovaZa();
    }

    /**
     * Create an instance of {@link Amendments.Head.GlasovaProtiv }
     * 
     */
    public Amendments.Head.GlasovaProtiv createAmendmentsHeadGlasovaProtiv() {
        return new Amendments.Head.GlasovaProtiv();
    }

    /**
     * Create an instance of {@link Amendments.Head.GlasovaSuzdrzani }
     * 
     */
    public Amendments.Head.GlasovaSuzdrzani createAmendmentsHeadGlasovaSuzdrzani() {
        return new Amendments.Head.GlasovaSuzdrzani();
    }

    /**
     * Create an instance of {@link Amendments.Head.Podnosilac }
     * 
     */
    public Amendments.Head.Podnosilac createAmendmentsHeadPodnosilac() {
        return new Amendments.Head.Podnosilac();
    }

    /**
     * Create an instance of {@link Amendments.Head.Propis }
     * 
     */
    public Amendments.Head.Propis createAmendmentsHeadPropis() {
        return new Amendments.Head.Propis();
    }

    /**
     * Create an instance of {@link Explanation.Razlog }
     * 
     */
    public Explanation.Razlog createExplanationRazlog() {
        return new Explanation.Razlog();
    }

    /**
     * Create an instance of {@link Explanation.ObjasnjenePredlozenogRjesenja }
     * 
     */
    public Explanation.ObjasnjenePredlozenogRjesenja createExplanationObjasnjenePredlozenogRjesenja() {
        return new Explanation.ObjasnjenePredlozenogRjesenja();
    }

    /**
     * Create an instance of {@link Explanation.Cilj }
     * 
     */
    public Explanation.Cilj createExplanationCilj() {
        return new Explanation.Cilj();
    }

    /**
     * Create an instance of {@link Explanation.UticajNaBudzetskaSredstva }
     * 
     */
    public Explanation.UticajNaBudzetskaSredstva createExplanationUticajNaBudzetskaSredstva() {
        return new Explanation.UticajNaBudzetskaSredstva();
    }

    /**
     * Create an instance of {@link Amendment.Body.Odredba }
     * 
     */
    public Amendment.Body.Odredba createAmendmentBodyOdredba() {
        return new Amendment.Body.Odredba();
    }

    /**
     * Create an instance of {@link Amendment.Head.Predmet }
     * 
     */
    public Amendment.Head.Predmet createAmendmentHeadPredmet() {
        return new Amendment.Head.Predmet();
    }

}
